//! midnad library: the daemon's modules, kept in a lib so they're testable.
//! See docs/ARCHITECTURE.md. Entry point: [`server::start`].
pub mod adopt;
pub mod agent_args;
pub mod agent_state;
pub mod agent_work;
pub mod auto_name;
pub mod clock;
pub mod conn;
pub mod daemon;
pub mod engine;
pub mod eventlog;
pub mod git;
pub mod global_hooks;
pub mod headless;
pub mod hooks;
pub mod images;
pub mod insights;
pub mod install;
pub mod keep_awake;
pub mod links;
pub mod local;
pub mod queue;
pub mod notify;
pub mod notify_media;
pub mod peer;
pub mod policy;
pub mod procs;
pub mod prompts;
pub mod pty;
pub mod restart;
pub mod resume;
pub mod rpc;
pub mod server;
pub mod state;
pub mod stream;
pub mod subagent_log;
pub mod term;
pub mod trust;
pub mod upgrade;
pub mod usage;
pub mod webhooks;

pub use daemon::Config;
pub use server::{Handle, start, start_with};
